push-image:
  needs: [train, test, build]
  runs-on: ubuntu-latest
  steps:
    - name: Repo Checkout
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v4
      with:
        name: my-build-package
        path: bike_sharing_api

    - name: Login to Docker Hub
      run: echo "${{ secrets.BIKE }}" | docker login -u "${{ secrets.BIKE_USERNAME }}" --password-stdin

    - name: Build the Docker image for FastAPI app
      run: docker build . -f Dockerfile -t ${{ secrets.BIKE_USERNAME }}/bikeshare-fastapi:latest

    - name: Push the Docker Image
      run: docker push ${{ secrets.BIKE_USERNAME }}/bikeshare-fastapi

    - name: Logout from Docker Hub
      run: docker logout
